### ISSUE TITLE
context->debug_mode not defined in F0038

### ISSUE THREAD

**Issue by Peter-Jacob** [adesutherland/CREXX#279] opened 2022-04-01 06:04 UTC
I just upgraded to the last F0038 version, and all my DEBUG macro calls don't compile with: 
**Use of undeclared identifier 'context'**

#define DEBUG(...) if (context->debug_mode) fprintf(stderr, __VA_ARGS__)

For the moment I can bypass the problem by changing the macro, but what is the solution?

**Comment by Peter-Jacob** [comment] 2022-04-01 06:15
it seems there is more broken:
```
C:\Users\PeterJ\CLionProjects\CREXX_F030\interpreter\rxvmintp.c:131:16: error: conflicting types for 'run'
 RX_FLATTEN int run(int num_modules, module *program, int argc, char *argv[],
                ^~~
In file included from C:\Users\PeterJ\CLionProjects\CREXX_F030\interpreter\rxvmintp.c:18:
C:\Users\PeterJ\CLionProjects\CREXX_F030\interpreter\rxvmintp.h:215:5: note: previous declaration of 'run' was here
 int run(rxvm_context *context, int argc, char *argv[]);
     ^~~
C:\Users\PeterJ\CLionProjects\CREXX_F030\interpreter\rxvmintp.c: In function 'run':
C:\Users\PeterJ\CLionProjects\CREXX_F030\interpreter\rxvmintp.c:296:63: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
             program[mod_index].segment.binary[j].impl_address =
                                                               ^
...
...
```

**Comment by rvjansen** [comment] 2022-04-01 09:27
Did not look at it, but in my book 'previous declaration was' always warrants a fresh git clone and checkout of the branch

**Comment by rvjansen** [comment] 2022-04-01 09:40
yes, I can confirm, I pulled on a machine I did not use for a while and had exactly the same errors. Did a fresh git clone git@github.com:adesutherland/CREXX.git crexx-f0038, cd crexx-f0038, git checkout feature/f0038, and then in my crexx_release directory, cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../crexx-f0038 && ninja && ctest --verbose ...
works like a charm.

**Comment by rvjansen** [comment] 2022-04-01 09:43
tentatively closing this issue as a (sort-of) duplicate of https://github.com/adesutherland/CREXX/issues/273 - reopen if you disagree.

**Closed by rvjansen** 2022-04-01 09:43 UTC
